services:
  frontend:
    image: 'ghcr.io/cleanwalk-org-asso/cleanwalk-org-v2/frontend:latest'
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.cleanwalk-front-recette.rule=Host(`cleanwalk.online`) || Host(`www.cleanwalk.online`)"
      - "traefik.http.routers.cleanwalk-front-recette.entrypoints=websecure"
      - "traefik.http.routers.cleanwalk-front-recette.tls.certresolver=letsencrypt"
      - "traefik.http.services.cleanwalk-front-recette.loadbalancer.server.port=80"
      - "traefik.http.services.cleanwalk-front-recette.loadbalancer.server.scheme=http"

    networks:
      - proxy
      - internal
    restart: always

  api:
    image: ghcr.io/cleanwalk-org-asso/cleanwalk-org-v2/api:latest
    env_file:
      - ./api/.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.cleanwalk-api-recette.rule=Host(`api.cleanwalk.online`)"
      - "traefik.http.routers.cleanwalk-api-recette.entrypoints=websecure"
      - "traefik.http.routers.cleanwalk-api-recette.tls.certresolver=letsencrypt"
      - "traefik.http.services.cleanwalk-api-recette.loadbalancer.server.port=8080"
      - "traefik.http.services.cleanwalk-api-recette.loadbalancer.server.scheme=http"

    networks:
      - proxy
      - internal
    restart: always


  database:
    image: postgres:18-alpine
    env_file:
      - ./database/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - internal
    restart: always


  redis:
    image: redis:8-alpine
    networks:
      - internal
    restart: always

volumes:
  db_data:

networks:
  proxy:
    external: true
  internal:
    driver: bridge