services:

  frontend:
    image: 'ghcr.io/cleanwalk-org-asso/cleanwalk-org-v2/frontend:latest'
    restart: always
    networks:
      - my_network

  api:
    image: 'ghcr.io/cleanwalk-org-asso/cleanwalk-org-v2/api:latest'
    volumes:
      - ./uploads:/app/uploads
    restart: always
    env_file:
      - ./api/.env
    networks:
      - my_network

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data-nginx:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - my_network

networks:
  my_network:
    external: true