services:

  frontend:
    image: 'ghcr.io/cleanwalk-org-asso/cleanwalk-org-v2/frontend:latest'
    restart: always
    networks:
      - my_network

  api:
    image: 'ghcr.io/cleanwalk-org-asso/cleanwalk-org-v2/api:latest'
    restart: always
    env_file:
      - ./api/.env
    networks:
      - my_network

networks:
  my_network:
    external: true